language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
git:
  depth: 25
  quiet: true
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - python setup.py install
script: pytest --cov=mylogging tests/
deploy:
  - provider: pypi
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    username: __token__
    password:
      secure: JhOc5ct8YRA/IlofNjkrlmODoefnZPLm1vSuPm4UdCsr2TdNko0jdyRv5egXUDx12WgInQTPQKCCmFGzhRfG6IYkfWw1FN7AtShpFhCeodXhqZi00K+27B3xpVdc0io9qEXPu5eOqPVYyA5XGlUGIpckLvuz/3Kc4On33oLlaj2kGrXo4XvBeqEm9Fm/yOGendYQ49VGQm8935871+J113V6MvktPYesnbi8jD/S8lLwAsUuAjdnNuEd25ygKdxMDi5OcxYzWsaDL+b55NZIVlVGLrROpXIeJ4hgUvTv4v2tplPFOyfdSO8/mW/NskRNrTRlr3Tiqtw3dsF5mPT2WChKMI9UdHQPwpzusRVpvBvDf+pLh73e82I5WmZfuxcorzla61qBnfH4KEA1fkBAAV+0YxDZSh4SpO6E6uWmM7WalaMjtb282I9ME3MwbqeC4DDWXDvlS/ocRFfFSyRGXmNKb8kM9EokWb5B9dmrmwBcTVFTC5KAMAN0agQzJ4E4NJw0pTBkIGK7jvcVveQHSqSlcxJteLAIl+qRcLgPELI6qkHOQOZ0WEQgswykqT9poz0mKtVbHCPiGJhfwkZ3+AVhLJsIZf1z19TsbjYUM5ez0x3iaWE+t8UvdNB8N85PjNfVVM48eHjNTzJzQbWa4MncyEzx1O5volpdpRvysB4=
    on:
      tags: true
      python: "3.7"
  - provider: releases
    github-token: "$GITHUB_TOKEN"
    skip_cleanup: false
    overwrite: true
    on:
      tags: true
      python: "3.7"
after_success:
  - bash <(curl -s https://codecov.io/bash)
