language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
git:
  depth: 25
  quiet: true
install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - python setup.py install
script: pytest --cov=mylogging tests/
deploy:
  - provider: pypi
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    username: __token__
    password:
      secure: "h+pf4yTAj9RaYE4kPipLL/MUhb05BQveOoGCd+klnNiC/tnXPI3/6d44sy5AfIolL5Nds9/C+UXp2oWpgGsep+hJNrvN2TPaj/StmvDSjFabb0rMSj47CzTHxaMQZ/Cv6UoYfvz1WD/dvA3YR8XGCzJiuCazFAopB5+HOzGe30rZWXPEx2YR63PnY7I6Gy/GOVeshfauDT8ws7LHObKTFkp0iOzlDxb7y7bFz0dY/MTW5IQjXp5suFEVZexB/0L+hq1g2qWw8gVNOMojuHBTaS2uUV8G36jT/4w4ZowaS6C8QS3nGoLNauPXMO/ws7XoHCb3a18Q8MH3Jpvnhi+i9IldQUXmC1SCMgTIQfQ/HykmJwrkjKZ7a12w6Yo5+JOg+lXbFO9RYoPv7ecDiO9VgVBH/4bC+SysZ0aJNioi3knD1zFiBNo9sHPD4hpwxkb9rwOCa5LHXWaFyCu5cJ50DKxi1fPSHf5TL2bR4lkk4PNjtr7j6a6GvZ421ZU2mRwwwFTvBNNq+1hhsBhhQTb3B3R1nmKSdVF252oC8xfXkcOXM12Hdaxr2wgo1rHGofYYUHQVFhrI3LLL6gvN8BVrPM/4BzVE0nGG5TxrX2eqGXmWKs6D3+QG2ptc751JTrGbpgGNtD6Qo/YHCNwmmQr8kuqeAr5HKHMqdQaEdEg36XM="
    on:
      tags: true
      python: "3.7"
  - provider: releases
    github-token: "$GITHUB_TOKEN"
    skip_cleanup: false
    overwrite: true
    on:
      tags: true
      python: "3.7"
after_success:
  - bash <(curl -s https://codecov.io/bash)
