language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

git:
  depth: 25
  quiet: true

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - python setup.py install

script: pytest --cov=predictit tests/

deploy:
  - provider: pypi
    skip_cleanup: true
    skip_existing: true
    distributions: "sdist bdist_wheel"
    username: "__token__"
    password:
      secure: "YPpJxIIbO4yPwRc9Btwl7q9k6Fykg7Uij0qQs2dukTnyRA4epJnFWToGmiRNKmqfu8vHbbN2akLo3DnJECxEOqpUz6jypJvsEkYMmkRVqoZLfNvLPWuRvzuyriFxybUkQy98WC/lV/ZmvjyTdh6lxE8WCFU9fsnblASJNrsmExMLxRQIx0BP0VYeHpDl2oUSLp5kGvbvawK+pG2MoIDmXeWeXAMNJ62syUF2IvEMQ50l4NLyA7aNuXHvdNwisxguvFV26Sh/Y3CVnM+4AciGEEr7mQomDk3z7RR5FxHzfJXCEJxMAR1c+vv0+cf6mGFlObGqlDgpqs+s6yvksVT1WEkO8gOST8NhrQm2vtN6uaYg0XUHJ8QfoLeSCUvJZlISl/ont2ktRKYtY1E306SuK7P/MNkylpjlynL4327sedQfSoN/XyFVNrT6SMNHTLIKQOyv9EOpfX5cmiB8X+QaTqsJZ0SZnmzRW5eJuheadSHSeJPfCYXFtViufqbVCNvxAjNHnPiNE6aoo4PjWPdF07gPCo5DXXHXKcjwWBPCASp5ab525impF9JZBTsLc+e2L6raJka0ljbhQVcV9i2x4KILNkMRE0lwa6AkWj01TPgQwtHgo9TG4MtMoK7qsp9oYWNHaNBPWWXT19oxNaQ+7uShq3TXG8yzLj4iO8EEHHc="
    on:
      tags: true
      python: "3.7"
  - provider: releases
    github-token: $GITHUB_TOKEN
    skip_cleanup: false
    overwrite: true
    on:
      tags: true
      python: "3.7"

after_success:
  - bash <(curl -s https://codecov.io/bash)
